experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.txt
    validation_path: ../data/{0}/val.txt
    test_path: ../data/{0}/test.txt
    side_information:
      - dataloader: VisualAttribute
        visual_features: ../data/{0}/image_feat
      - dataloader: TextualAttribute
        textual_features: ../data/{0}/text_feat
  dataset: office
  top_k: 50
  evaluation:
    cutoffs: [10, 20, 50]
    simple_metrics: [Recall]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.VBPR:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: True
        validation_rate: 190
        validation_metric: Recall@20
        restore: False
      lr: 0.005
      modalities: ('visual','textual')
      loaders: ('VisualAttribute','TextualAttribute')
      epochs: 190
      factors: 64
      batch_size: 1024
      l_w: 1e-2
      comb_mod: concat
      seed: 123
    external.MMGCN:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: True
        validation_rate: 90
        validation_metric: Recall@20
        restore: False
      lr: 1e-5
      epochs: 90
      num_layers: 3
      factors: 64
      factors_multimod: (256, None)
      batch_size: 1024
      aggregation: mean
      concatenation: False
      has_id: True
      modalities: ('visual','textual')
      loaders: ('VisualAttribute','TextualAttribute')
      l_w: 1e-5
      seed: 123
    external.GRCN:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: True
        validation_rate: 160
        validation_metric: Recall@20
        restore: False
      lr: 0.001
      epochs: 160
      num_layers: 2
      num_routings: 3
      factors: 64
      factors_multimod: 128
      batch_size: 1024
      aggregation: add
      weight_mode: confid
      pruning: True
      has_act: False
      fusion_mode: concat
      modalities: ('visual','textual')
      loaders: ('VisualAttribute','TextualAttribute')
      l_w: 1e-5
      seed: 123
    external.LATTICE:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: True
        validation_rate: 190
        validation_metric: Recall@20
        restore: False
      epochs: 190
      batch_size: 1024
      factors: 64
      lr: 0.001
      l_w: 1e-5
      n_layers: 1
      n_ui_layers: 2
      top_k: 20
      l_m: 0.7
      factors_multimod: 64
      modalities: ('visual','textual')
      loaders: ('VisualAttribute','TextualAttribute')
      seed: 123
    external.MGAT:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: True
        validation_rate: 60
        validation_metric: Recall@20
        restore: False
      lr: 0.00001
      epochs: 60
      num_layers: 2
      factors: 64
      factors_multimod: (256, 100)
      batch_size: 1024
      modalities: ('visual','textual')
      loaders: ('VisualAttribute','TextualAttribute')
      l_w: 1e-5
      seed: 123
